name: Build

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches: ['dev', 'release', 'master']

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run build CI
        run: |
          RunUAT\Build.bat GreenOneEditor Win64 Development -project="C:\Users\SERV-ADMIN\Desktop\GreenOneProject\GreenOneGit\GreenOne.uproject" -WaitMutex -FromMsBuild
