name: Build

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches: ['dev', 'release', 'master']

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name : Debug Git
        run: git log

      - name: Run build CI
        run: |
          U:\UE_5.1\Engine\Build\BatchFiles\Rebuild.bat GreenOneEditor Win64 Development -project="C:\Users\SERV-ADMIN\Desktop\GreenOneProject\GreenOneGit\GreenOne.uproject" -WaitMutex -FromMsBuild
        shell: cmd