name: Build

on:
  push:
    branches:
      - 'feature-*'
  pull_request:
    branches: ['dev', 'release', 'master']

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name : Debug Git
        run: git log

      - name: Run build CI
        run: |
          cd "U:\UE_5.1\Engine\Build\BatchFiles\" 
          U:
          Build.bat GreenOneEditor Win64 Development -project="U:\actions-runner\_work\GreenOne\GreenOne\GreenOne.uproject" -WaitMutex -FromMsBuild
        shell: bash